# This workflow will do a clean install of node dependencies, cache/restore them, run tests and eslint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: |
        npm ci
        npm run eslint
        npm run test
        npm run build
